/**
 * Post action types
 *
 * @type {{SET_POSTS: string}}
 */
export const types = {
    GET_BOOKSLIST: 'GET_BOOKSLIST',
    GET_BOOKSLIST_SUCCESS: 'GET_BOOKSLIST_SUCCESS',
    GET_THEME: 'GET_THEME',

    GET_BOOOK_DETAILS: 'GET_BOOOK_DETAILS',
    GET_BOOOK_DETAILS_SUCCESS: 'GET_BOOOK_DETAILS_SUCCESS',
    GET_BOOOK_DETAILS_FAIL: 'GET_BOOOK_DETAILS_FAIL',
};
